config/routes.rb
Rails.application.routes.draw do

  scope "/admin" do
    devise_for :users
  end
  #devise_for :users

  get 'homes/index'
  root to: "homes#index"

  namespace :admin do
    root to: "message#index"
    #mesajlar
    resources :message, only: [:show, :index]
    #kategoriler
    resources :category, except: [:show]
    #sayfalar
    resources :page, except: [:show]
    #haberler
    resources :news
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/news.rb
class Admin::News < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/category_controller.rb
class Admin::CategoryController < AdminController
  before_action :authenticate_user!
  before_action :set_admin_category, only: [:destroy, :edit, :update]
  #get admin/category
  def index
    @categories = Category.all
  end
  # GET /admin/category/1
  def new
  end
  # POST /admin/categoru
  def create
    @category = Category.new(post_params)
    respond_to do |format|
      if @category.save
        format.html {redirect_to admin_category_index_path, notice: "Kaydınız basarili" }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    #@category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_category_index_path
  end

  def edit
  end

  def update
    if @category.update(params[:post].permit(:title, :description, :isVisible))
      redirect_to admin_category_index_path
    else
      render 'edit'
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :description, :isVisible)
  end

  def set_admin_category
    @category = Category.find(params[:id])
  end

end

app/controllers/admin/message_controller.rb
class Admin::MessageController < AdminController
  before_action :authenticate_user!
  def index
    @messages = Message.all.order("created_at DESC")
  end

  def show

  end
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < AdminController
  before_action :set_admin_news, only: [:show, :edit, :update, :destroy]

  # GET /admin/news
  # GET /admin/news.json
  def index
    @admin_news = Admin::News.all
  end

  # GET /admin/news/1
  # GET /admin/news/1.json
  def show
  end

  # GET /admin/news/new
  def new
    @admin_news = Admin::News.new
  end

  # GET /admin/news/1/edit
  def edit
  end

  # POST /admin/news
  # POST /admin/news.json
  def create
    @admin_news = Admin::News.new(admin_news_params)

    respond_to do |format|
      if @admin_news.save
        format.html { redirect_to @admin_news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @admin_news }
      else
        format.html { render :new }
        format.json { render json: @admin_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/news/1
  # PATCH/PUT /admin/news/1.json
  def update
    respond_to do |format|
      if @admin_news.update(admin_news_params)
        format.html { redirect_to @admin_news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_news }
      else
        format.html { render :edit }
        format.json { render json: @admin_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/news/1
  # DELETE /admin/news/1.json
  def destroy
    @admin_news.destroy
    respond_to do |format|
      format.html { redirect_to admin_news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_news
      @admin_news = Admin::News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_news_params
      params.require(:admin_news).permit(:title, :content)
    end
end

app/controllers/admin/page_controller.rb
class Admin::PageController < AdminController
  before_action :set_page, only: [:edit, :update, :destroy]
  def index
    @pages = Page.all
  end

  def new
    @categories = Category.all
  end

  def create
    @page = Page.new(post_params)
    respond_to do |format|
      if @page.save
        format.html {redirect_to admin_page_index_path, notice: "Kaydınız basarili" }
      else
        @categories = Category.all
        format.html { render :new }
      end
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    if @page.update(params[:post].permit(:title, :content, :category_id))
      redirect_to admin_page_index_path
    else
      @categories = Category.all
      render 'edit'
    end
  end

  def destroy
    @page.destroy
    redirect_to admin_page_index_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :category_id)
  end

  def set_page
    @page = Page.find(params[:id])
  end





end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin/application'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout :layout_by_resource

  private
  def layout_by_resource
    if devise_controller?
      "admin/login"
    else
      "application"
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/admin/category_helper.rb
module Admin::CategoryHelper
end

app/helpers/admin/message_helper.rb
module Admin::MessageHelper
end

app/helpers/admin/news_helper.rb
module Admin::NewsHelper
end

app/helpers/admin/page_helper.rb
module Admin::PageHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu
    @categories = Category.where(isVisible: "1") 
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/category/edit.html.erb
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to "Geri", admin_category_index_path %>
    </li>
    <li class="breadcrumb-item active">Kategori Ekle</li>
  </ol>
  <div class="row">
    <div class="col-12">
      <%= @category.inspect   %>
      <%= form_for :post, url:admin_category_path, method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :title, "Başlık",:class =>"from-group"%><br>
          <%= f.text_field :title, class: "form-control", :value =>@category[:title]%>
        </div>
        <div class="form-group">
          <%= f.label :description, "Açıklama", :class =>"from-group"%><br>
          <%= f.text_field :description, class: "form-control", :value =>@category[:description] %>
        </div>

        <div class="form-group">
          <%= f.label :isVisible, "Üst menü görünürlüğü", :class => "from-control" %><br>
          <%= f.check_box :isVisible, {checked: @category[:isVisible] }, "true", "false" %>
        </div>

        <div class="form-group">
          <%= f.submit "Güncelle", :class => "btn btn-primary"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/category/index.html.erb
<div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">


      <%= link_to new_admin_category_path, :class => "btn btn-primary btn-small", :style => "position: absolute; right: 2%; font-size: 12px" do %>
        <i class="fa fa-plus"></i>
        Yeni Kategori Ekle
      <% end %>

      <li class="breadcrumb-item active">
        Kategoriler
      </li>
    </ol>
    <div class="row">
      <div class="col-12">

        <div class="mb-3">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
              <tr>
                <th>Menu</th>
                <th>Başlık</th>
                <th>Açıklama</th>
                <th>Kategori</th>
                <th>Oluşturulma tarihi</th>
                <th>Seçenekler</th>
              </tr>
              </thead>
              <tbody>
              <% @categories.each do |category| %>
                <tr>
                  <td><%= category.isVisible%></td>
                  <td><%= category.title %></td>
                  <td><%= category.description[0,25] %></td>
                  <td></td>
                  <td><%= category.created_at %></td>
                  <td>
                    <%= link_to edit_admin_category_path(category) do%>
                      <i class="fa fa-edit"></i>
                    <% end %>

                    <%= link_to admin_category_path(category), method: :delete, data: { confirm: 'Are you sure?' } do%>
                      <i class="fa fa-trash"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/admin/category/new.html.erb
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">



    <li class="breadcrumb-item">
      <%= link_to "Geri", admin_category_index_path %>
    </li>
    <li class="breadcrumb-item active">Kategori Ekle</li>
  </ol>
  <div class="row">
    <div class="col-12">

      <%= form_for :post, url:admin_category_index_path do |f| %>
      <div class="form-group">
        <%= f.label :title, "Başlık",:class =>"from-group"%><br>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description, "Açıklama", :class =>"from-group"%><br>
        <%= f.text_field :description, class: "form-control" %>
      </div>


        <div class="form-group">
          <%= f.label :isVisible, "Üst menü görünürlüğü", :class =>"from-control"%><br>
          <%= f.check_box :isVisible , {}, "true", "false" %>
        </div>

      <div class="form-group">
        <%= f.submit "Kaydet", :class => "btn btn-primary"%>
      </div>

    <% end %>
    </div>
  </div>
</div>

app/views/admin/message/index.html.erb
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <a href="#" class="btn btn-primary btn-small" style="position: absolute; right: 2%; font-size: 12px">
      <i class="fa fa-plus"></i>
      Yeni Kategori Ekle
    </a>
    <li class="breadcrumb-item">
      <a href="index.html">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Blank Page</li>
  </ol>
  <div class="row">
    <div class="col-12">

      <div class="mb-3">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
              <th>Kimden</th>
              <th>Konu</th>
              <th>Email</th>
              <th>Oluşturulma tarihi</th>
              <th>Seçenekler</th>
            </tr>
            </thead>
            <tbody>
            <%= @messages.each do |message| %>
              <tr>

                <td>
                  <% message.name %></td>
                <td>
                  <% message.title %></td>
                <td>
                  <% message.email %></td>
                <td>
                  <% message.created_at %></td>
                <td>
                  <i class="fa fa-edit"></i>
                  <i class="fa fa-delete"></i>
                  <i class="fa fa-search"></i>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/admin/news/_form.html.erb
<%= form_with(model: admin_news, local: true) do |form| %>
  <% if admin_news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_news.errors.count, "error") %> prohibited this admin_news from being saved:</h2>

      <ul>
      <% admin_news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :admin_news_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :admin_news_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/news/edit.html.erb
<h1>Editing Admin News</h1>

<%= render 'form', admin_news: @admin_news %>

<%= link_to 'Show', @admin_news %> |
<%= link_to 'Back', admin_news_index_path %>

app/views/admin/news/index.html.erb
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">


    <%= link_to new_admin_news_path, :class => "btn btn-primary btn-small", :style => "position: absolute; right: 2%; font-size: 12px" do %>
      <i class="fa fa-plus"></i>
      Yeni Haber Ekle
    <% end %>

    <li class="breadcrumb-item active">
      Haberler
    </li>
  </ol>
  <div class="row">
    <div class="col-12">

      <div class="mb-3">
        <div class="table-responsive">
            <p id="notice"><%= notice %></p>
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Content</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @admin_news.each do |admin_news| %>
                  <tr>
                    <td><%= admin_news.title %></td>
                    <td><%= admin_news.content[1..25] %></td>
                    <td>
                      <%= link_to edit_admin_news_path(admin_news) do%>
                          <i class="fa fa-edit"></i>
                      <% end %>
                      <%= link_to admin_news_path(admin_news) , method: :delete, data: {confirm: 'Are you sure?'} do%>
                        <i class="fa fa-trash-o"></i>
                      <% end %>
                      <%= link_to admin_news do %>
                        <i class="fa fa-search"></i>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>

            <br>


        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/news/new.html.erb
<h1>New Admin News</h1>

<%= render 'form', admin_news: @admin_news %>

<%= link_to 'Back', admin_news_index_path %>

app/views/admin/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_news.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @admin_news.content %>
</p>

<%= link_to 'Edit', edit_admin_news_path(@admin_news) %> |
<%= link_to 'Back', admin_news_index_path %>

app/views/admin/page/edit.html.erb
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">



    <li class="breadcrumb-item">
      <%= link_to "Geri", admin_page_index_path %>
    </li>
    <li class="breadcrumb-item active">Sayfa Ekle</li>
  </ol>
  <div class="row">
    <div class="col-12">

      <%= form_for :post, url:admin_page_path, method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :title, "Başlık",:class =>"from-group"%><br>
          <%= f.text_field :title, class: "form-control", :value => @page[:title] %>
        </div>

        <div class="form-group">
          <%= f.label :content, "Açıklama", :class =>"from-group"%><br>
          <%= f.text_field :content, class: "form-control", :value => @page[:content] %>
        </div>

        <div class="form-group">
          <%= f.label :category_id, "Kategori", :class => "form-group" %><br>
          <%= f.select :category_id, @categories.all.collect {|p| [p.title, p.id] }, id: :category_id, :selected=>@page[:category_id] %>
        </div>

        <div class="form-group">
          <%= f.submit "Kaydet", :class => "btn btn-primary"%>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/admin/page/index.html.erb
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">


    <%= link_to new_admin_page_path, :class => "btn btn-primary btn-small", :style => "position: absolute; right: 2%; font-size: 12px" do %>
      <i class="fa fa-plus"></i>
      Yeni Sayfa Ekle
    <% end %>

    <li class="breadcrumb-item active">
      Sayfalar
    </li>
  </ol>
  <div class="row">
    <div class="col-12">

      <div class="mb-3">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
            <tr>
              <th>Başlık</th>
              <th>Kategori</th>
              <th>Oluşturulma tarihi</th>
              <th>Seçenekler</th>
            </tr>
            </thead>
            <tbody>
            <% @pages.each do |page| %>
              <tr>
                <td><%= page.title %></td>
                <td><%= page.category[:title] %></td>
                <td><%= page.created_at %></td>
                <td>
                  <%= link_to edit_admin_page_path(page) do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to admin_page_path(page), method: :delete, data: {confirm: 'Are you sure?'} do %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/page/new.html.erb
<div class="container-fluid">
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">



    <li class="breadcrumb-item">
      <%= link_to "Geri", admin_page_index_path %>
    </li>
    <li class="breadcrumb-item active">Sayfa Ekle</li>
  </ol>
  <div class="row">
    <div class="col-12">

      <%= form_for :post, url:admin_page_index_path do |f| %>
      <div class="form-group">
        <%= f.label :title, "Başlık",:class =>"from-group"%><br>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :content, "Açıklama", :class =>"from-group"%><br>
        <%= f.text_field :content, class: "form-control" %>
      </div>

      <div class="form-group">
          <%= f.label :category_id, "Kategori", :class => "form-group" %><br>
          <%= f.select :category_id, @categories.all.collect {|p| [p.title, p.id] },:class => "form-control", id: :category_id %>
      </div>

      <div class="form-group">
        <%= f.submit "Kaydet", :class => "btn btn-primary"%>
      </div>

    <% end %>
    </div>
  </div>
</div>

app/views/homes/blank.html.erb
<div id="detailContainer">
  <div id="detailLeft">
    <div class="detailTitle cozumler">
      <h1>Boş sayfa</h1>
      <div class="saver hiddenText">&nbsp;</div>
    </div>
    <div class="detailHTML">
      <h2>Başlık</h2>
      <p>İçerik</p><br />
      <h1>Homes#index</h1>
      <p>Find me in app/views/homes/index.html.erb</p>
    </div>
  </div>
  <div id="detailRight">
    <div class="rightMenuBG">&nbsp;</div>
    <div class="rightMenu">
    </div>
    <div class="rightBulten"> <a href="ebulten.html">
      <h2>E-Bülten'e<br />
        Abone Olun!</h2>
    </a>
    </div>
  </div>
  <div class="saver hiddenText">&nbsp;</div>
</div>
<div class="saver hiddenText">&nbsp;</div>
</div>

app/views/homes/index.html.erb
<div id="homeSliderContainer">
  <div id="homeSlider">
    <div class="item">
      <%= image_tag("temp/slide_1.jpg") %>
    </div>
    <div class="item">
      <%= image_tag("temp/slide_2.jpg") %>
    </div>
    <div class="item">
      <%= image_tag("temp/slide3.jpg") %>
    </div>
    <div class="item">
      <%= image_tag("temp/slide_4.jpg") %>
    </div>
  </div>
  <div class="saver hiddenText">&nbsp;</div>
</div>
<div id="homeContentContainer">
  <div id="homeContent">
    <div id="homeBottomContent">
      <div id="homeBottomVideo" class="item">
        <h2>KAZANCILAR<b>TANITIM VİDEOSU</b></h2>
        <a href="https://www.youtube.com/watch?v=q1jOyjjPWIk" rel="prettyPhoto[]" style="background: transparent no-repeat scroll center top">
          &nbsp; </a>
      </div>
      <div id="homeBottomHaber" class="item">

        <h2>KAZANCILAR<b><a href="#">HABERLER & DUYURULAR</a></b></h2>
        <div class="haberContent">

          <?php foreach($news as $item) { ?>
          <span class="itemHaber">
              <span class="date"></span>
              <a href="#">
                <span class="haberText"><p></p></span>
              </a>
            </span>
          <?php } ?>

        </div>
      </div>
      <div class="saver hiddenText">&nbsp;</div>
    </div>
  </div>
  <div class="saver hiddenText">&nbsp;</div>
</div>
<div class="saver hiddenText">&nbsp;</div>

app/views/layouts/_bottom.html.erb
<div id="footerContainer">
  <div id="footerContent">
    <div class="footerMenu">
      <a href="<?=base_url()?>" >Anasayfa <span>&nbsp; / &nbsp;</span></a>
      <a href="<?=base_url()?>haberler" >Haberler <span>&nbsp; / &nbsp;</span></a>
      <a href="<?=base_url()?>iletisim" >Bize Ulaşın <span>&nbsp; / &nbsp;</span></a>
      <span class="footerSocial">
          <a href="#" target="_blank">
            <img src="<?= base_url() ?>assets/images/icon/face.png" alt="" title="" />
            <%= image_tag("icon/face.png", :alt=>"") %>
            <span>&nbsp; / &nbsp;</span>
          </a>
          <a href="#" target="_blank">
            <img src="<?= base_url() ?>assets/images/icon/linkedin.png" alt="" title="" />
            <%= image_tag("icon/linkedin.png", :alt=>"") %>
            <span>&nbsp; / &nbsp;</span>
          </a>
          <a href="#"  target="_blank">
            <img src="<?= base_url() ?>assets/images/icon/youtube.png" alt="" title="" />
          </a>
        </span>
      <span class="saver hiddenText">&nbsp;</span>
    </div>
    <div class="footerBottom">
      <p><b>KAZANCILAR HAYVANCILIK</b>  .. .. .. Ticaret A.Ş. Atatürk Cad. Atatürk İş Merkezi No:81 Kat:7 Merkez 11881 ANKARA </p>
      <p>KAZANCILAR &copy; 2016  Tüm hakları saklıdır.</p>
      <p style="color:#df7b8e; font-size:14px; font-weight:bold;">ÇAĞRI MERKEZİ  : 0850 000 00 00</p>
    </div>
  </div>
  <div class="saver hiddenText">&nbsp;</div>
</div>
</body>
</html>

app/views/layouts/_top.html.erb
  <div class="tool-box">
    <a href="<?= base_url() ?>iletisim">Bize Ulaşın</a>
    <input type="submit" value="EN" class="langLink">
    <span class="search" id="my-button"><a href="#"></a></span>
    <span class="span">
      <input type="text" id="my-input" class="searchTxt" data-search-path="<?= base_url('search') ?>" placeholder="Arama...">
    </span>
  </div>
  <div id="headerContainer">
    <div class="logo">
        <%= image_tag("logo/logo2.png", :alt=>"", :class=>"logoImg") %>
        <%= image_tag("logo/mobilemenu-logo2.png", :alt=>"", :class=>"mobileLogoImg") %>
    </div>
    <a href="javascript:;" class="mobileMenuOpen">
      <span class="mobileMenuTitle">MENÜ</span>
      <%= image_tag("button/mobileMenu.png", :alt=>"" ) %>
      <span class="saver hiddenText">&nbsp;</span>
    </a>
    <div class="headerRight">
      <div class="headerSubMenuContent">
        <div class="subMenu">
          <ul>
            <li class="level0 menu1">
              <%= link_to "Anasayfa", root_path %>
            </li>
            <% menu.each do |item| %>
            <li class="level0 menu1">
              <%= link_to item.title %>
            </li>
              <% end %>
          </ul>
        </div>
        <div class="saver hiddenText">&nbsp;</div>
      </div>
      <div class="headerMenu">

      </div>
      <div class="saver hiddenText">&nbsp;</div>
    </div>
    <div class="saver hiddenText">&nbsp;</div>
  </div>

app/views/layouts/admin/_bottom.html.erb
<footer class="sticky-footer">
  <div class="container">
    <div class="text-center">
      <small>Copyright © Your Website 2018</small>
    </div>
  </div>
</footer>
<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fa fa-angle-up"></i>
</a>


<!-- Logout Modal-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <a class="btn btn-primary" href="#">Logout</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin/_top.html.erb
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <a class="navbar-brand" href="index.html">Kazancılar Hayvancılık</a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">



      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Kategoriler">
        <%= link_to admin_category_index_path, :class => "nav-link" do %>
          <i class="fa fa-fw fa-table" aria-hidden="true"></i>
          <span class="nav-link-text">Kategoriler</span>
        <% end %>
      </li>

      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Mesajlar">
        <%= link_to admin_message_index_path, :class => "nav-link" do %>
          <i class="fa fa-envelope-square" aria-hidden="true"></i>
          <span class="nav-link-text">Mesajlar</span>
        <% end %>
      </li>

      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Sayfalar">
        <%= link_to admin_page_index_path, :class => "nav-link" do %>
          <i class="fa fa-fw fa-file" aria-hidden="true"></i>
          <span class="nav-link-text">Sayfalar</span>
        <% end %>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
        <a class="nav-link" href="tables.html">
          <i class="fa fa-newspaper-o"></i>
          <span class="nav-link-text">Haberler</span>
        </a>
      </li>
      
    </ul>
    <ul class="navbar-nav sidenav-toggler">
      <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler">
          <i class="fa fa-fw fa-angle-left"></i>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">


      <li class="nav-item">
        <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
          <i class="fa fa-fw fa-sign-out"></i>Logout</a>
      </li>
    </ul>
  </div>
</nav>